### ISSUE TITLE
CW bank B のメッセージ　＃１の件

### ISSUE THREAD

**Issue by JO3JYE** [jr8ppg/zLog#103]
CQモードでもSPモードでも、CW　BANK　Ｂの#1が、F1キーで送信できなくなっています。
bank　Bを選んでいても、F1を押すとBANK　Aの#1となります。
マウスでボタンをクリックした場合はBANK　Ｂの#1が出ます。
本件は、Magical　Callingを実装してからだと思います。

RUNしているにもかかわらず、BANK　Bをセレクトしている使い方を見たことがあります。（見てからから、なるほど！と思い、自分自身そうしていることもあります)
runしているとCQは単発よりループで出すから、CTRL+ZかSHIFT+Z。コールされたら押すのはTAB、最後は↓キーですし。
BANK　Aを表に出す必要がないよね…ということでした。

ただ、CQモードとSPモードの切り替えトリガにF1キーも含まれているので、条件整理も必要かもしれません。

**Comment by jr8ppg** [comment]
今開発中の物からF1のデフォルト割り当てが#116のバンクAのCQ送信に変わっています。ご指摘の通りMagical Callingで変更した物です（CQモードの切り替えトリガのため）
これを#010のバンクAのメモリ内容の送信01にすると従来通りの動きになります。
CTRL+ZでCQかけるなら、それで問題ないと思います。

**Comment by JO3JYE** [comment]
説明ありがとうございました。
設定変更でokとなりました。
脱線しますが、クイックリファレンスが長らく更新されていないと思います。
デフォルトから変わらない部分とkey-editで変えた部分を足し合わせて、自分用のクイックリファレンスを作る機能というのは他の方からの需要あるでしょうか？個人的にはほしいのですが。

**Comment by jr8ppg** [comment]
クイックリファレンスとは ZLOGHELP.TXT のことですかね？

**Comment by JO3JYE** [comment]
はい、その通りです。よろしくお願いします。

**Comment by jr8ppg** [comment]
zlog_keyedit.exeから出力すると良いですかね。とりあえず話題が違うのでこのIssueはクローズします。
