### ISSUE TITLE
zlog_keyedit.exeよりキーアサインの一覧を出力する

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#105]
zlog_keyedit.exeよりキーアサインの一覧を出力することができないか

**Comment by jr8ppg** [comment]
ZLOGHELP.TXTの内容
こんな感じ

> ロギングに関するキー操作
> ------------------------
> SHIFT+B  バンド変更
> SHIFT+M  モード変更
> SHIFT+R  了解度(R)変更
> SHIFT+S  信号強度(S)変更
> SHIFT+P  パワーコード変更
> Alt+O    オペレータ変更
> 
> 入力と編集に関するキー操作
> --------------------------
> Alt+C    コールサインフィールドに移動
> Alt+N    ナンバーフィールドに移動
> Alt+M    メモフィールドに移動
> Alt+R    RSTフィールドに移動
> Ctrl+A   フィールドの先頭に移動
> Ctrl+E   フィールドの最後に移動
>

**Comment by JO3JYE** [comment]
対応ありがとうございました。
こちらのイメージ通りの実装です！
これで、zlog_keyeditでキーアサインを書き換えまくっても変更箇所を失念して判らなくなることは回避できるでしょう。hi
マルチOPのときはキーアサインの情報共有ができて良いかと思います。

**Comment by jr8ppg** [comment]
了解です。とりあえずはこれでbeta2にします。
