### ISSUE TITLE
Voice再生中にshift+xでRIGを切り替えると、Voice再生が止まる

### ISSUE THREAD

**Issue by 7M4KSC** [jr8ppg/zLog#111]
RIG1:IC-756PRO 50MHz
RIG2:IC-7000 144MHz
で、RIG1でVoice key再生中に、shift+xでRIG2に切り替えると、voice再生が止まる。

**Comment by jr8ppg** [comment]
一応は現象が再現した

**Comment by jr8ppg** [comment]
止めている箇所判明
https://github.com/jr8ppg/zLog/blob/7ed5825622a671f1edabb7eb63e6d2b457455cb4/zlog/main.pas#L5509

RIG切り替え時に周波数が変わるのでCQモードからSPモードへ切り替わる。その際にCQを停止している。
設定でCQを止めるか止めないか選べるようにする方向。
