### ISSUE TITLE
Win10(version 2004)以降で、無変換でPTTが効かない

### ISSUE THREAD

**Issue by 7M4KSC** [jr8ppg/zLog#112]
この問題の背景はこれ。
[https://mindtech.jp/?p=1513](https://mindtech.jp/?p=1513)
仮想キーコードはこれ。
[http://7ujm.net/C++/vkey.html](http://7ujm.net/C++/vkey.html)
物理的な無変換キーにVKEY:無変換では無く、VKEY:IME OFF(これは新しいVKEYだと想定される)
が割り当てられてしまっている。
最新のVirtual key codeはこれ。
[https://docs.microsoft.com/ja-jp/windows/win32/inputdev/virtual-key-codes](https://docs.microsoft.com/ja-jp/windows/win32/inputdev/virtual-key-codes)
関連：これがMSが何をしようとしてるのかが、一番分かり易いかも。キーボードのレイアウトを変えようとしている。
[https://docs.microsoft.com/ja-jp/windows-hardware/design/component-guidelines/keyboard-japan-ime](https://docs.microsoft.com/ja-jp/windows-hardware/design/component-guidelines/keyboard-japan-ime)

**Comment by jr8ppg** [comment]
申告されている事象より、
メインウインドウ
CallsignEditはImeModeがimDisable
NumberEditはImeModeがimClose
この違いと思われる。

imDisableの時はMS-IMEの影響を受けない模様。

**Comment by jr8ppg** [comment]
memo

変換キー
VK_CONVERT

無変換キー
VK_NONCONVERT

**Comment by jr8ppg** [comment]
今のところ、ImeModeをimDisableにする方向

**Comment by 7M4KSC** [comment]
了解しました、MS改変キーボードが出荷されたら、考えるということで、当面imDisableで良いかと。
