### ISSUE TITLE
Operator名に"~"(チルダー)を含むと

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#123]
Operator名に"~"(チルダー)を含むと、zServerへ接続した時のログマージの際にウインドウがポップアップする
（「リストのインデックスが範囲を超えています (17).」の発生は確認した。それ以外に何かあるかどうかは未確認）
テストしたOperator名は「~UJS」

**Comment by jr8ppg** [comment]
こんばんは。
ご指摘の通りです。zLogからZServerへの送信データは TILDE SEPARATED VALUESなのでデータに~を含んではいけないのです。
含むことによって項目にずれが生じて誤動作などの動きになっています。
とりあえずはOP名などに~を含まない様に使って下さい。

**Comment by jr8ppg** [comment]
いつのバージョンか忘れたけど、SEPARATORになる文字が含まれる場合はQUOTEするようにしているので今のバージョンでは問題なく動きます。
（少なくともQSOデータは問題ない）

**Comment by jr8ppg** [comment]
済
