### ISSUE TITLE
zlog.exeと同じフォルダに配置したZLOG.SPCがロードされない

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#128]
2.6.0.4の不具合報告です。

https://github.com/jr8ppg/zLog/wiki/Super-Check-(N%EF%BC%8B1)#%E8%A8%AD%E5%AE%9A
>  ZLOG.SPCとMASTER.SCPは下図のフォルダ欄で入力したフォルダか、zlog.exeと同じフォルダに配置します。

[Misc]タブのフォルダ欄が空欄の場合、zlog.exeと同じフォルダにZLOG.SPCを配置しても読み込まれません。
ZLOG.SPCのパスをフォルダ欄に指定すれば読み込まれます。

なお、MASTER.SCPは、zlog.exeと同じファイルに配置すれば、[Misc]タブのフォルダ欄が空欄でも正常に読み込まれます。

**Comment by jr8ppg** [comment]
レポートありがとうございます。
原因わかりました。

**Comment by jr8ppg** [comment]
ここでExitしたらだめで、strStartFolderにExtractFilePath(Application.EXEName)を入れればOKかな
https://github.com/jr8ppg/zLog/blob/master/zlog/UzLogSpc.pas#L341

**Comment by jj1cvh** [comment]
0bb9a5c を使って正常動作を確認しました。
ご対応ありがとうございました。
