### ISSUE TITLE
「memo」欄に「(0.0)」が毎入力ごとに入力される

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#131]
1交信の入力完了時にmemo欄に(0.0)が入力されるようになってしまった。

継続はしていますが再現していなません。次のような操作を行いました。
「File-New Contest-」で開いたzLog Menuで[Cancel]キーを押して終了させて(勝手に終了する)
次回起動すると、1交信ごとです。

ContestはDX Peditionと全市全郡を選んでみました。
zlog.iniを作り直せば元に戻るようです（自信なし）。

**Comment by jj8dan** [comment]
具体的にはこんな感じです
![zLog_(0 0)](https://user-images.githubusercontent.com/79432176/113585551-55c98480-9667-11eb-9aec-261dba4678e7.png)

**Comment by jr8ppg** [comment]
こんばんは。レポートありがとうございます。

確認したところ下記の条件で再現しました。
１．リグコントロールを行う設定になっている
２．通信条件が違うなどの理由でリグから情報が取れていない（周波数表示は00000.000KHz）
３．Options-Rig controlタブ-Record rig frequency in memoがON

zlog.iniを削除すると上記１と３がクリアされますので起こらなくなります。

対処
通信条件などを見直してリグから周波数を取得できる様にして下さい（上記２）

です。

**Comment by jr8ppg** [comment]
そうそう、(0.0)はリグの周波数です。正しく取れていれば、(7123.4)と言った感じで表示されます。

**Comment by jj8dan** [comment]
こんばんは。
その通りです。1.と2.  リグコントロールON のままリグの電源がオフになっていた。 3. ☑ Record rig frequency in memo。
言い訳をするとzlog_v26_beta4_release_note.pdfの31ページ「#100 CABRILLOファイルにACTUAL FREQUENCYを出力する」を読んで（紙ログで周波数細かく書いとく癖があるので）これ便利だなで終わってしまいmemo欄に影響するまで読み下せませんでした。早とちりで申し訳ないです。FAQになりそうな気がします。
