### ISSUE TITLE
CWモード時の「Stop CW」ボタンの色

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#132]
version: 2.6.0.3 - 2.6.0.5

CWモード時の「Stop CW」ボタンの色が常に赤ですね。
ver 2.6.0.2までと同様に、CWメッセージ送出中、およびCtrl-Z/Shift-ZのループCQ送出中は赤、それ以外はグレーとして頂けますと幸いです。

**Comment by jr8ppg** [comment]
現象確認。WinKeyer対応で混入した模様。

**Comment by jr8ppg** [comment]
#110 の対応でエンバグした模様。と言うか今まではたまたまうまく動いていた感じ。

**Comment by jr8ppg** [comment]
修正完了

**Comment by jj1cvh** [comment]
060c8f8 をビルドし、正常動作を確認しました。
ご対応ありがとうございました。
