### ISSUE TITLE
memo欄右の余白

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#133]
version: 2.3.0.5 - 2.6.0.5

zLog起動直後のmemo欄の幅が狭く、右側に余白が生じています。

zLogウィンドウの幅をマウスで変更するとmemo欄の幅が最適化され余白が無くなります。
引き続き、zLogウィンドウの幅を一番狭くして起動時と同じ幅にしても、余白は生じません。
zLogを再起動すると、再び余白が生じます。

令和版の最初のリリース2.3.0.5と、最新のベータ版2.6.0.5で確認しました。
zLog 2.2eでは余白は生じません。
単なる見た目の問題ですので、検討いただく優先度は低で結構です。

**Comment by jr8ppg** [comment]
現象確認。

**Comment by jr8ppg** [comment]
修正完了

**Comment by jj1cvh** [comment]
80e679f をビルドし、正常動作を確認しました。
ご対応ありがとうございました。

**Comment by jj1cvh** [comment]
version: 2.6.0.6
Ctrl+S   表示フォントサイズの変更
をすると、再びmemo欄の右に余白が生じました。

**Comment by jr8ppg** [comment]
memoの入力欄ではなくてリスト側のmemoと了解。

**Comment by jj1cvh** [comment]
0bd5743 をビルドし、
Ctrl+S 表示フォントサイズの変更
を実施した時にQSO済みリストのmemo欄の右に余白が生じる現象が解決していることを確認しました。
ご対応ありがとうございました。
