### ISSUE TITLE
画面外にウィンドウが出てしまった時に戻らないウィンドウが

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#135]
デスクトップの広い画面で運用したフォルダをそのままノートPCに持っていき狭い画面になるとウィンドウが外に出ます。
困ったことに元に戻せない場合が生じました。
Windows一般に画面外にウィンドウが出たときはそのウィンドウにフォーカスして[Alt], {Space], [M], マウスで少し動かして, [カーソルキー] と順番に押すと画面内に戻ってきます。コンテスト選択画面、メインウィンドウなどはそう動作します。
困ったのはメインウィンドウの[Windows]で外に出た【CW Message Pad】 がフォーカスしようとしてもメインウィンドウが動作してしまい[Alt]→[Space]が効かず[CW Message Pad]が二度と画面内に戻りません。[Alt]+[Tab]を使っても【CW Mesasge Pad】にAlt→Spaceは効きません。【CW Message Pad】が偶然この現象に引っかかったのか【CW Message Pad】固有なのかはまだ未検証です。
zlog.iniを消してしまえば復帰しますが設定が多い人は大変です。
今のところどう動作するのが適当かは思いつかないのですけれども。

**Comment by jr8ppg** [comment]
モニター右側と下側は、ウインドウ左上が１ピクセルでもモニターに入っていると引き戻さないので。ウインドウの右端又は下端がモニターからはみ出ている場合は強制的にモニター内に引き戻すことにしてみる。
