### ISSUE TITLE
Device cannot be identified.エラーが発生する

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#140]
一部機種でDevice cannot be identified.エラーが発生する。
HID-compliant fidoと言うデバイスみたい。
レッツノートCF-MX5、CF-C2
関連 #107 
回避ヒント https://github.com/bitdump/BLHeli/issues/199#issuecomment-266233320

**Comment by jr8ppg** [comment]
回避ヒントの手法を試したところ、エラー回避ができ、なおかつUSBIF4CWも動作した。

**Comment by jr8ppg** [comment]
本来ならJEDIが直すべき物でしょう

**Comment by jr8ppg** [comment]
とりあえず回避できた（はず）
Debugモード実行時はエラーダイアログが出ます。
https://github.com/jr8ppg/zLog/tree/usbundefinedfix

@jj1cvh さんお試し願えますか。

**Comment by jj1cvh** [comment]
Version 2.6.0.6 で下記2機種でDevice cannot be identified.エラーが発生した件、usbundefinedfix 0504938 をビルドして所有者に試していただき、エラーが発生しなくなったことを確認してもらいました。

SurfacePro3 (win10 20H2)
CF-RZ8HDEQR (win10 20H2)

なお、CF-RZ8ではUSBIF4CWを接続し、ロギングやキーイングも問題なく動作することも確認していただきました。

**Comment by jr8ppg** [comment]
ご確認ありがとうございます。
とりあえずこの修正内容で進めます。

**Comment by jr8ppg** [comment]
一旦クローズで
