### ISSUE TITLE
バンドスコープ表示時にスポッターのコールサインを表示してほしい

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#144]
改良案
1.表示桁内に追加
2.カーソルを該当コールに当ていると表示される内容に追加

**Comment by jr8ppg** [comment]
まずはToolTip内表示で

**Comment by jj1cvh** [comment]
バンドスコープの[Current]にスポッターのコールサインが表示される場合とされない場合があります。

スポットが上がったタイミングで当該バンドになっている場合は、スポッターのコールサインが表示されます。
スポットが上がったタイミングで別バンドになっている場合は、当該バンドに切り替えてもスポッターのコールサインが表示されません。
また、スポッターのコールサインが表示されていても、いったん他バンドに切り替えてから当該バンドに戻ると、スポッターのコールサインが表示されなくなります。

**Comment by jr8ppg** [comment]
現象確認

**Comment by jr8ppg** [comment]
済

**Comment by jj1cvh** [comment]
Version 2.7.1.1で正常動作を確認しました。
ご対応ありがとうございました。
