### ISSUE TITLE
winkeyer使用時にTABキー動作が不完全となることがある

### ISSUE THREAD

**Issue by JO3JYE** [jr8ppg/zLog#145]
winkeyer使用時に、ＴＡＢキーを押してもコールサインだけ送出し、ナンバーが欠落することがある。
当方では、以下の操作で再現しています。

1.「ESCキー」を押す
2.コールサイン入力　(入力済みを利用しても同じ)　←F1やCTRL+Zなどの操作でも同じ。
3.「TABキー」を押す。
4.　コールサインを送った後、ナンバーを送らずに停止。
　　入力のフォーカスはナンバーのEDIT欄へ移動。
5.もう一回「TABキー」を押す。
6.正常動作。

　どうやら「ESCキー」を押した後、最初の「TABキー」の時に、コールサインのみとなるようです。

**Comment by JO3JYE** [comment]
一度ESCキー(STOPボタン)を押すと　FWkAbort := True　。wkの中断フラグが立ちます。
この状態が残ったまま、TABキーを押して　処理に入ると、コールサインは送出されても、ナンバーを送る　CallsignSentProc　が呼び出されてもの、FWkAbortのフラグが生きているので、何もしないでプロセスを終えていました。

OnTabPress　のイベント処理内に、　FWkAbort := False　を追加しました。
場所は5105行目の後、wkの処理部分冒頭です。

**Comment by jr8ppg** [comment]
修正ありがとうございます。
確認しました。
