### ISSUE TITLE
FT-817のリグコントロールにおいて38400bpsの動作が不完全な件

### ISSUE THREAD

**Issue by JO3JYE** [jr8ppg/zLog#158]
FT-817のリグコントロールで通信速度を38400BPSにすると、周波数変更、モード変更後からリグの状態が正しく読み出せなくなる。9600BPSでも同様に、変更後の読み出しに失敗することがある。フォームにあるRESETボタンを押すと回復する。

FT-857では、9600BPSはOK。38400BPSはFT-817と同じく失敗する。

**Comment by JO3JYE** [comment]
5/8-9開催の関西VHFコンテスト前に気が付き、修正したコードで関西VHFコンテストに参加。
FT-857DMにて前半9600BPS、後半に38400BPSを使用し、当方の個体では問題解消となっています。

**Comment by jr8ppg** [comment]
了解しました
