### ISSUE TITLE
ICOM機のモードをzLogで変更してもMode欄に反映されない

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#169]
(動作環境)
Windows 10 2004 64bit, USBシリアルIF(FT232RL)

zLog version: 2.5.0.0 Beta1 - 2.7.0.0
zlog.iniを消去してから以下を設定
 Rig1: COM5 19200 IC-756ProII
 Use Transceieve Mode 有効
 Get band and mode alternately 無効

(現象) 例えばzLog、リグ本体ともCWモードの場合
1. QSO入力行のMode欄をクリックし、SSBに変更すると、リグのモードはSSBに切り替わるが、zLogのMode欄は一瞬SSBに切り替わってすぐCWに戻ってしまう。
2. SHIFT+Mを押すと、リグのモードはSSBに切り替わるが、zLogのMode欄は一瞬SSBに切り替わってすぐCWに戻ってしまう。
3. 上記1. 2.の操作時、Rig Control画面のMode表示はCWのまま。

(補足)
- リグ本体のモードボタンでModeを切り替えると、正常にzLogに反映。
- 2.5.0.0 Beta1の頃から発生。2.4.1.0とzLog 2.2eは正常。

**Comment by jj1cvh** [comment]
追記
RigのCI-V TransceiveはONの状態で検証しました。

**Comment by jr8ppg** [comment]
#171 , #174 の対応で良くなったとのこと
