### ISSUE TITLE
タスクバーに入らないウィンドウがある

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#173]
メインウィンドウの「Windows」から呼び出せるウィンドウのうち、2つだけ最小化した時タスクバーに入らない。
確認したバージョン：2.7.0.1 x86, x64 の２種類
【入らない】
Z-Server Messages
Function Key Panel
タスクバーに入らず画面左下に張り付く。
![zLog-Windows_CannotInTaskbar](https://user-images.githubusercontent.com/79432176/121784052-a40d7d80-cbec-11eb-9a54-a3d283f462bb.png)

**Comment by jr8ppg** [comment]
済
