### ISSUE TITLE
Z-Server Messagesウィンドウの動き

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#189]
Z-Server Messagesウィンドウは、一度IMEオンにしたら他ウィンドウから戻った時にIMEオンになってほしい

**Comment by jr8ppg** [comment]
従来からImeModeの値を保存してウインドウがアクティブになった際に保存したImeModeの値に戻す処理があったが、期待した動きでは無いので削除した。（ImeModeは初期値で現在値では無いため）

**Comment by jj1cvh** [comment]
47cb4f3 をビルドし、期待していた動作になることを確認しました。
ご対応ありがとうございました。
