### ISSUE TITLE
Z-Serverのバンド表示をオペレータ表示に切り替える機能がほしい

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#190]
Z-Serverのバンド表示をオペレータ表示に切り替える機能がほしい

**Comment by jr8ppg** [comment]
間違えた #191 でコミットしてしまった

**Comment by jj1cvh** [comment]
最新コミット 98f873f をビルドし、期待していた動作になることを確認しました。
従来の[OK]ボタンは不要ですので、[OK]ボタンを削除してBand/PCNAME/OPNAME/CALLの選択ボックスを追加するのは、ナイスアイデアだと思います。

1点、以前のバージョンから生じていますが、惜しい点がありまして、zLogのQSO入力行で10GHz&Upを選択すると、Z-Server Messages画面のIDが
10GMHz>
となります。

実用上は何ら問題ありませんが、一応ご報告まで。

**Comment by jr8ppg** [comment]
10Gの表記は昔からここの定義ですね。
色々なところで使われていて長くするとあちこちで影響出そうです。
https://github.com/jr8ppg/zLog/blob/master/zlog/UzlogConst.pas#L72

**Comment by jj1cvh** [comment]
いえ、長さの話ではなく、「10GMHz」じゃなくて「10GHz」ですよね、ということです。

**Comment by jr8ppg** [comment]
おっと、それは気がつきませんでした。
格好悪いですね。

**Comment by jj1cvh** [comment]
ちなみに、Z-Server 2.2fの画面上でも「10GMHz」と表示されます...

**Comment by jr8ppg** [comment]
まあ、同じ仕組みですからね、、、
MHz取って良いですかね？

**Comment by jj1cvh** [comment]
「10G」でも良いですよ。
Z-Server画面の「Current Frequencies」ウィンドウは、「10G」と表示しますね。

**Comment by jj1cvh** [comment]
最新コミット 22fd181 をビルドし、期待していた動作になることを確認しました。
プロンプトの文字数を少なくして6文字＋>でも良いかなとは思いますが、これでもOKです。
ご対応ありがとうございました。
