### ISSUE TITLE
Multi-Opで起動したときに、最終OpのWAVファイルが選択されていない

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#193]
zLogのMulti-Opで起動したときに、読み込んだログの最終OpのままだとPhoneのwavファイルが再生されない。
zLogで読み込んだログの最終OpがQSO行のOp欄に表示されますが、当該Opのwavファイルが再生されません。
QSO行で同じOpを再選択するとwavファイルが再生されるようになります。

**Comment by jr8ppg** [comment]
WAVファイルというか、最終QSOのOPが選択されていない。

**Comment by jj1cvh** [comment]
最新コミット 98f873f をビルドし、正常にWAVファイルが再生されるようになったことを確認しました。
ご対応ありがとうございました。
