### ISSUE TITLE
optionウィンドウを閉じた後、元のRIGへ戻りたい

### ISSUE THREAD

**Issue by JO3JYE** [jr8ppg/zLog#197]
現状では、RIG2の状態で、otpionウィンドウを開いた後、閉じてメインフォームへ戻るとRIG１になります。
でれきば、元のRIGへ戻れないでしょうか？
RIG1以外の時は、予期せぬところへQSYしてしまうこともあります。
(MAXRIGを３，４と増やしても同じです)

**Comment by jr8ppg** [comment]
V2.9で解消していると思いますのでクローズします．．．
