### ISSUE TITLE
HAMLOG用のCSV出力機能

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#205]
1列目　コールサイン
2列目　交信年月日（YY/MM/DD）　※「YYYY/MM/DD」でもOKだった記憶
3列目　交信時分（HH:MM*）　※「*」にはJST…J・UTC…U
4列目　相手局へ送ったレポート
5列目　相手局からもらったレポート
6列目　周波数
7列目　電波型式
8列目　相手局の運用地コード
9列目　相手局の運用地グリッドロケータ
10列目　QSLマーク　※取りあえず「J」を入れておけばOK
11列目　相手局の名前・名称
12列目　相手局の運用地
13列目　Remarks1
14列目　Remarks2
15列目　なんかの識別子

15列目の識別子：
　基本的に国内局…0・海外局…8
　でもそれ以外の場合もある

**Comment by jr8ppg** [comment]
MemoをRemarks1とRemarks2のどちらに出力するか

**Comment by jr8ppg** [comment]
15列目の内容については、ハムログ相談室ーNo.17309 「EXCEL出力 Flagについて」参照
→過去ログは流れている模様

**Comment by jj1cvh** [comment]
[No.17309] EXCEL出力 Flagについて
http://www.hamlog.com/hamlogbbs/forum/wforum.cgi?pastlog=0014&no=17309&act=past&mode=allread#17309

**Comment by jr8ppg** [comment]
なるほど。その辺取り入れてみます。

**Comment by jr8ppg** [comment]
いったん済み
