### ISSUE TITLE
Cluster画面等の設定をzlog.iniに保存

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#215]
zLog令和の新機能に関して、初期状態から設定を変更しても、次回起動時に初期状態に戻ってしまう設定がいくつかあります。
以下については一旦設定したら継続的に使い＆他のPCにもzlog.iniを配布して同じ設定をマルチオペで使用したいのですが、zlog.iniに保存するように改善していただけませんでしょうか？

[Windows] >
Cluster画面: チェックボックス5個
Z-Server Messages画面: チェックボックス3個、選択ボックス1個

**Comment by jr8ppg** [comment]
これは全市全郡までにあった方がよさそうですね。
