### ISSUE TITLE
SCPファイルが大きい際のSuperCheckについて

### ISSUE THREAD

**Issue by jucky154** [jr8ppg/zLog#220]
いつもお世話になっております。JS2FVOです。
ACAGで使った際に、SuperCheckを使ったもののloading...と表示されたまま使用できませんでした。
SCPファイルが4MBと大きくそこら辺が原因かもしれません。（同じファイルを旧zLogで読み込んだ場合は使用できることは確認しております）
ご確認のほどよろしくお願いします。

**Comment by jr8ppg** [comment]
ようやく修正

**Comment by jucky154** [comment]
ありがとうございます。　V2.7.1.6リリース時に確認させていただきます。

**Comment by jr8ppg** [comment]
済
