### ISSUE TITLE
ＳＳＢモードでのＴＡＢキーの動作が以前と違う

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#352]
ＳＳＢモードでのＴＡＢキーの動作が異なっています。
コールサイン入力フィールドでコールを入力後、ＴＡＢキーを押下しても音声は再生されるが、コンテストナンバーフィールドにカーソルが移動しません。（音声ファイルを設定しておけば、Ｆ２の音声ファイルは再生されています。）

Version 2.8.0.10 では正常、それ以降ＮＧ。
#285 の影響では無いか。

**Comment by jr8ppg** [comment]
現象確認できない。TABキーでナンバー欄に移動する。
どなたか追試希望。

**Comment by jj1cvh** [comment]
Version2.8.3.0で、zlog.iniを削除した状態でzLogを起動してみました。
F2の音声ファイル設定有無にかかわらず、SSB時にTABキーを押してもコール欄から移動しませんね。

**Comment by jr8ppg** [comment]
現象確認しました。全然ダメ。

**Comment by jr8ppg** [comment]
結局のところ、TContestのリファクタリング時に修正ミスった模様。 #353 の修正で対応。https://github.com/jr8ppg/zLog/commit/cdb7def7032331dca6bf71141f2cbb592a7b0365
