### ISSUE TITLE
JARL用Cabrillo出力

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#363]
Cabrillo出力時にJSTでも出せるとありがたいです．
これはJARL4大でCabrillo提出時にUTCではなく，JSTが指定されているためです（AAはUTC）．
本来のCabrillo仕様とは異なるので，あまりいいことではないと思いますが．JSTでも出せるオプションがあればと思っています．

https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/e-log_cabrillo.txt

**Comment by jr8ppg** [comment]
ACAGの場合、Sent NRにPower Codeを付けられない

**Comment by jkitagawa** [comment]
いい感じです．ありがとうございます．
