### ISSUE TITLE
強制確定の不具合

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#375]
QSO入力時にShift+Enterで強制確定すると、それ以降のQSOもForcedになる。

**Comment by jucky154** [comment]
このバグはField Dayのバージョンでは確実に存在しました
（それ以前にもあったような気がしますが、その辺はあやふやです）

**Comment by jr8ppg** [comment]
修正済

**Comment by jr8ppg** [comment]
うーん、周波数も同様でした。（周波数を記録しない設定の場合）

**Comment by JO3JYE** [comment]
修正ありがとうございました。周波数を記録しない場合の動作確認できました。

**Comment by jr8ppg** [comment]
確認ありがとうございます。
