### ISSUE TITLE
Rigの切り替えをShift+Xをデフォルトとする

### ISSUE THREAD

**Issue by 7M4KSC** [jr8ppg/zLog#39]
現状、Alt+.がRigの切り替えに割り当てられているが、これを旧zLog for Win95と同じく、Shift+xキーとする。
[ML:00012]

**Comment by jr8ppg** [comment]
修正済み
https://github.com/jr8ppg/zLog/commit/eab8e26e663d1106c013efcce313cab0c25e68d7
