### ISSUE TITLE
zLog用TELNETクライアント

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#41]
V2.6
zLog用TELNETクライアントを追加します

→追加(11/2)

https://github.com/jr8ppg/zLog/commit/a063c95abd2052536a0e92b738fc3a0b69afe7c5

**Comment by jj1cvh** [comment]
zLogバージョン: v2510 branch 8b922c8
現象: zlog_telnet ビルドエラー
> プロジェクト "zlog_telnet.dproj" のビルドが終了しました。 -- 失敗
> ビルドに失敗しました。
> zlog_telnet.vrc(64): error RC2135: file not found: zlog.ico

補足: zlogフォルダのzlog.icoをzlog_telnetにコピーしたらビルドできました。
