### ISSUE TITLE
フォントによって下の方が切れてしまう

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#435]
Consolasフォントを使った場合に，コールサイン入力欄やSCPウィンドウの縦幅を
小さくした時にQの下が途切れてOに見えることがある。

スーパーチェックウインドウ／Ｎ＋１
![image](https://github.com/jr8ppg/zLog/assets/56021425/f0f7e7f5-f652-479e-a6ed-76e8e191c590)

**Comment by jr8ppg** [comment]
修正後はこんな感じで
![image](https://github.com/jr8ppg/zLog/assets/56021425/f667280d-43fa-4c9c-9f47-c61bb9c534bc)

**Comment by jkitagawa** [comment]
これでいいです．

**Comment by jr8ppg** [comment]
確認OK
