### ISSUE TITLE
ポータブル付コールサインのspcからのナンバー入力

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#465]
zlog.spcからのナンバー入力はコールサインをポータブルまで含めて一致した物を採用したい。
一致する物がなかった場合はナンバー入力しない。
```
zlog.spcに，例えば，以下のような記述があったとします．

JF3EBO 24M
JF3EBO/6 47M

この状態でcallにJF3EBO/6と入力した場合に，現状だと24Mが入ります．
これを47Mが入るようにしていただけないでしょうか．

JF3EBO/6が複数並んでいる場合は，

JF3EBO 24M
JF3EBO/6 46M
JF3EBO/6 47M

/6で一番上にある46Mでいいと思います．

```

**Comment by jj8dan** [comment]
根が深い問題な気がしてきました。
JJ8DAN 112M
JJ8DAN 0105M
JJ8DAN 205D
JJ8DAN 01
どれを選べばいいのでしょう？

**Comment by jr8ppg** [comment]
コンテストに合わせてSPCファイルを作ればいいので、最初に出てきたもので良いのです。
例題の４つは全て違うコンテストのNRですね。
