### ISSUE TITLE
Z-LINK関係設定など見直し

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#480]
・ホストを入力していないとアプリケーションエラーになる
・Z-Serverとの接続状態
など

**Comment by jj8dan** [comment]
Z-Server接続時にMergeかDownloadを選ぶBOXが出ますが、ここでCancelしてもZ-Linkは切れない（すでに繋がっている）（Cancelするとログがどうなるかはログに関するコマンドが送られないので不明、不定？）。ここのCancelの意味はZ-Linkは取りやめるの意味が正しいのではないか。

![2023-08-27 (1)](https://github.com/jr8ppg/zLog/assets/79432176/ad361771-a384-4b97-befe-ee04d4a9eabf)

**Comment by jr8ppg** [comment]
#510 も関係あり。
Z-Serverホスト未設定の場合はメッセージを表示するように変更。
