### ISSUE TITLE
DATファイルをビルトインする

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#490]
ACAG.DAT,XPO.DAT,ARDX.DAT,IOTA.DAT,ARRL10.DATの５ファイルをzlog.exeファイルにビルトインする。
zlog.exeと同じフォルダにあれば、そちらを使用。無ければビルトインされたファイルを使う。

**Comment by jr8ppg** [comment]
済

**Comment by jj8dan** [comment]
オプション:各種フォルダ:CFG/DAT で設定したフォルダに入れている場合はどう優先しましょう？
%ZLOG_ROOT% があまりごちゃごちゃしないようにACAG.DAT,XPO.DAT,ARDX.DAT,IOTA.DAT,ARRL10.DAT は
CFG/DATで設定したフォルダに入れてしまって%ZLOG_ROOT%からは消してしまってます。

**Comment by jr8ppg** [comment]
下記の順でファイルの存在をチェックして存在すればそれをロードします。最終的に無ければビルトインされたファイルを使います。
１．CFG/DATフォルダ
２．zlog.exeがあるフォルダ（%ZLOG_ROOT%で無いのはバグかな）
