### ISSUE TITLE
spotを取得するまでの間、Z-Serverに接続しない件の改善

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#496]
spotを取得するまでの間、Z-Serverに接続しないため、正常にZ-Serverに接続できる状態かどうかが分からない(#447,#480関連)
実際、Z-ServerのIPアドレスを誤って設定していたことに気付かず、コンテスト開始後、1時間以上たってから設定ミスに気付いた。
Z-Server再起動時にも、zlog_telnetのZ-Linkが切断されていることに気付かなかった。
Z-Serverには即接続する方が良いのではないか。

**Comment by jj1cvh** [comment]
Changed: ZServerへのconnectタイミング変更 
https://github.com/jr8ppg/zLog/commit/807e9fa3c9498916f5b5e0ec63a066f3a41f0a16
にて対応

**Comment by jr8ppg** [comment]
済
