### ISSUE TITLE
マルチオペ：スクロールが新QSOで戻ってしまう

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#497]
Z-Link時に、新しいQSOが届くと画面スクロールが最新に戻ってしまいます。
Dupe言われて過去QSOを探しにいっている時に新QSOが届くと修正ができないのです。
（現状のままでやるなら、一旦、Z-Link切ればいいのですが）
ただ、画面スクロールを過去のままにいつまでもするのも困りものです。
例えば、スクロールそのままでTwitter的に「新しいQSOがあります」とうながすとかですかね。

**Comment by jr8ppg** [comment]
> Dupe言われて過去QSOを探しにいっている時に新QSOが届くと修正ができないのです。
DUPEと言われたら「ありがとうございました」でスルーするのが良いと思いますが、それはそうとして問題点はわかりました。
対応考えます。

**Comment by jj8dan** [comment]
自分ではDupeのつもりでなくてDupe言われると過去QSOのコールサインをミスコピーしているので探しにいかなければ1QSO逃してしまいます。

**Comment by jr8ppg** [comment]
過去のQSOは直さないで、新しいQSOをそのままログインしてしまえばいいのですよ。

**Comment by jj8dan** [comment]
何時何分Dupeです、ありがとうございました、QRZ と言われて交信成立しないのでそこに新しいQSOはないのです。もう一回交信できれば過去QSOを訂正する必要はないです。最近はDupeを許容するスタイルの方が多いですが中にはかたくなな方もいます。と、いった背景があります。

**Comment by jr8ppg** [comment]
呼びに回って相手側がDUPEなんですね。私は暇なときならともかく、面倒なのでそのままにしてますわ。
KCJみたいなログ照合のある場合は別ですけど、uniqueになるだけなので。

**Comment by jr8ppg** [comment]
こんな感じかな
![image](https://github.com/jr8ppg/zLog/assets/56021425/c17b509c-525e-479e-a7af-35b2df6f6a91)

**Comment by jr8ppg** [comment]
交信リストスクロールのみの場合に対応

**Comment by jr8ppg** [comment]
実際にXPOコンテストで使ってみると、他のzLogでの交信データを受信すると、何でも無いのにお知らせがでてウザいので、表示条件の見直しを行った。

**Comment by jj8dan** [comment]
> 実際にXPOコンテストで使ってみると、他のzLogでの交信データを受信すると、何でも無いのにお知らせがでてウザいので、表示条件の見直しを行った。

私のところでもなんでもないのに出ました。コールサイン欄でスペース押すと消えました。

**Comment by jr8ppg** [comment]
済み
