### ISSUE TITLE
Z-Server接続時の処理に「接続のみ」を追加する

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#510]
Z-Server接続時の処理に、「Merge」「Download」があるが、どちらもやりたくない場合のために「Connect only」を追加する。
Mergeは処理に時間がかかり、コンテストのある局面ではやらない方が良い場合がある。
DownloadはzLog側のみにあるQSOが無くなってしまう。

**Comment by jr8ppg** [comment]
こんな感じで
![image](https://github.com/jr8ppg/zLog/assets/56021425/8a719f30-6a04-432f-b225-74b0076ba4d4)

**Comment by jr8ppg** [comment]
これはOKでしょう

**Comment by jr8ppg** [comment]
デフォルトは「マージ」に変更
![image](https://github.com/jr8ppg/zLog/assets/56021425/53733f28-867f-4fd0-bd09-0e94ba9e20b3)

**Comment by jj8dan** [comment]
OKを押すと３択した１つが動作するのですが、Cancelを押した場合はどう動作します？
今まで(例えば2.8.6.1)は、

- すでにZ-Linkは確立している
- マージかダウンロードを選んでOKを押すとそれが実行される
- Cancelを押すと今回の「接続のみ」動作が結果的にが実施される（接続自体はキャンセルされない）。

今後Cancelはどう扱いますか？Disconnectします？それかCancelボタン自体なくすか。
(ウィンドウ左上にはすでに「Connected...」と出ているのでわざわざDisconnectしなくてもいいか)

**Comment by jr8ppg** [comment]
Cancelは「接続のみ」と同じですね。3番目です。「×」も同じです。

「OK」なら接続、「Cancel」なら接続しないの方が一般的は解釈なのでそうしたいですね。
