### ISSUE TITLE
シリアルNOのコンテストでQSO削除した場合のシリアルNO巻き戻し

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#566]
案
（１）最後のQSOが削除された場合、そのシリアルNOは無かったことにする（巻き戻す）
（２）最後のQSOのシリアルNOを進めた場合、その修正を受け入れる。

**Comment by jr8ppg** [comment]
（１）は実装した

**Comment by JO3JYE** [comment]
(1)の動作、確認いたしました。ありがとうございます。
