### ISSUE TITLE
マルチオペ：Function Key Panel にオペレータごとに設定したマクロが表示されない

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#568]
マルチオペ：Function Key Panel にオペレータごとに設定したマクロが表示されない
Function Key Panelに表示されるのは「運用設定」ーCW/RTTYタブのマクロで
実際に送出されるのはオペレータごとに設定したCWマクロ
オペレータごとに設定したマクロを表示させたい

**Comment by jr8ppg** [comment]
うーん、忘れてましたな。
