### ISSUE TITLE
PTT ON/OFFをリグコマンドで行う

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#571]
リグコントロールのコマンドでPTTがON/OFFできるとリモート運用で活用出来る。

PTT制御コマンド
ICOM:1c-00-00/1c-00-01
YAESU:RX;/TX;
KENWOOD:TX0;/TX2;

**Comment by jj1cvh** [comment]
ICOM機は以下のコマンドのようです。
1C0000 受信
1C0001 送信

**Comment by jr8ppg** [comment]
情報ありがとうございます。
送受信の切り替え・・・ですね。
