### ISSUE TITLE
KENWOODのリグコントロールでの不具合

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#589]
初期状態が2）で何かの操作で1）になったとのこと。
1）RTSの設定をNoneにしてもハンドシェイクにしてもフロー制御Noneになる
2）RTSの設定をハンドシェイクにしてもNoneにしてもフロー制御ハードウェアになる

再現確認まだ

**Comment by jj8dan** [comment]
2.9.1.1
|I/F|Serial|RTS|DTR|Rig to PC|PC to Rig|Hang-up|
|-|-|-|-|-|-|-|
|USB-Serial|9pin full|ハンドシェイク|None|OK|OK|None|
|USB-Serial|9pin full|None|None|OK|OK|None|
|USBIF4CW Gen.3|TXD,RXD,GND| ハンドシェイク|None|Fail|Fail|ハードウェア設定を選ぶと発生、USBケーブルを抜くと回復|
|USBIF4CW Gen.3|TXD,RXD,GND| None|None|OK|OK|None|

|Magical Calling|メインダイヤルを回す度にTS-570からBeep|
|-|-|
|☑使用する|鳴る|
|☐使用する|鳴らない|

やっとまとまりました。TS-570からBeepが鳴るのはMagical Callingを使うと発生します。これをシリアルポートのRTS制御と混同していたので訳がわからなくなっていました。

**Comment by jr8ppg** [comment]
KENWOODはPCからコマンドを送るといちいちピッってなるので、メニューでOFFにすると良いですよ。
TS-570はメニュー01です。

**Comment by jr8ppg** [comment]
対応なし。done
