### ISSUE TITLE
CW/PHツールバーの表示

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#641]
CW/PHツールバーの表示をON/OFFすると表示できなくなる、との評を聞いて
試してみました。事象発生後に4パターンキャプチャしました。
V2.9.1.5

![MenuON_CWON](https://github.com/user-attachments/assets/945f4ea3-02f5-47ef-a193-fec64cc755f2)
![MenuON_CWOff](https://github.com/user-attachments/assets/39d6f799-cad0-47a0-9a67-6a15945ac851)
![MenuOff_CWON](https://github.com/user-attachments/assets/740152ee-6f2e-4086-81b8-5e50df8002d7)
![MenuOff_CWOff](https://github.com/user-attachments/assets/fb329d1d-bf3e-4e9f-a79b-fbc79eeacf08)

**Comment by jr8ppg** [comment]
済
