### ISSUE TITLE
RTTYの動作確認

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#652]
最新バージョン（V2.9）でMMTTYとの連係動作ができるかどうか改めて確認。

**Comment by jr8ppg** [comment]
動作チェックレポート
問題点
1. $Mが展開されない
1. 起動・終了時にApplication errorが発生する

改善点
1. 左クリックでのコールサイン取り込み
1. 連続CQ

**Comment by jkitagawa** [comment]
$Mが展開されるようになったこととアプリケーションエラーが出なくなったことを確認しました．

**Comment by jr8ppg** [comment]
確認ありがとうございます。
