### ISSUE TITLE
MMTTY：コールサインの抽出を改良

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#668]
#652 より
今は DE から始まるものをコールサインとして抽出している。
DEが無くてもコールサインらしきものを抽出できないか。

**Comment by jr8ppg** [comment]
TTTYConsole.RXChar()を直せば良い

**Comment by jr8ppg** [comment]
英字と数字で構成される単語を抽出。英字のみはNG,数字のみもNG
それっぽくなってきた
![image](https://github.com/user-attachments/assets/4e1fdad6-f1dc-4334-9fc4-010c9f18ddbc)

**Comment by jkitagawa** [comment]
DEなしでもコールサインが取り込めていて改善されているのを確認しました．ありがとうございます．

**Comment by jr8ppg** [comment]
確認ありがとうございます。それっぽくなりました。次は連続CQの方に入ります。
