### ISSUE TITLE
zLog CSV(*.csv)のAG欄Areaの扱い

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zLog#671]
zLog CSV(*.csv)のAG欄Areaの扱い
CallSign 欄が7K1~, 7K2~, 7K3~, 7K4~
だとAreaが
1, 2, 3, 4 
となってしまう。
7L~, 7M~, 7N~
でも同じ
7L1~/1, 7L2~/1, 7L3~/1, 7L4~/1
だと
1, 1, 1, 1
となる。
実害は少ないですが、コンテスト後の検証で引っかかりました。

**Comment by jr8ppg** [comment]
7K1–7N4は1エリアですね。

**Comment by jr8ppg** [comment]
修正完了
