### ISSUE TITLE
プラグインインストールのエラー

### ISSUE THREAD

**Issue by irukabando** [jr8ppg/zLog#701]
zLog portal の安定板 zLog をインストールし，各種設定 -> プラグインマネージャーから zLog additional O/I をインストールするとエラーが出てしまいます。他にも高校コンテストでもエラーが出てしまいます。
対処法などありませんでしょうか。

**Comment by jr8ppg** [comment]
これはこちらでも把握していまして、サーバー側の問題なので連絡はしてあるのですが中々直りませんね、、、

**Comment by JG1VPP** [comment]
ご無沙汰しております
手元の環境（2.8.4.7）で試しましたが、特に問題なくプラグインをインストールできました

こちらに報告いただきました内容では原因が特定できませんので、スクリーンショットなど共有いただけますでしょうか？

### 再現手順

#### zLog additional I/O

1. zlog.exe単体を適当なフォルダに配置して起動します（クリーンな状態）
2. Plugin ManagerでzLog additional I/Oをインストールします
3. Import/Exportメニューで選択可能なファイル形式が増えています（プラグインは期待通りに動作）

ただし、このIssueとは別の問題と思いますが、Import/Exportが期待通りに動作しなくなっており、その原因は別途調査します。

#### 高校コンテスト

1. zlog.exe単体を適当なフォルダに配置して起動します（クリーンな状態）
2. Plugin Managerで高校コンテストをインストールします
3. New contestでUser defined contestからhstest.cfgを選びます（CFGファイルは2の操作で自動的にインストールされます）
4. 適当なQSOを入力すると、規約に沿って得点計算されます（プラグインは期待通りに動作）

**Comment by JG1VPP** [comment]
> これはこちらでも把握していまして、サーバー側の問題なので連絡はしてあるのですが中々直りませんね、、、

これはDLLのリリース時にmd5チェックサムが https://pkg.zlog.org/market.json に反映されない問題と認識しています。https://github.com/nextzlog/zylo/commit/7982afa8f31526ac158d3b15cca7a35db1a4d3c6 にて対応済みです。

**Comment by jucky154** [comment]
@JG1VPP 
私がこのチェックサムで問題が起きると報告を受けているのですが、2.9.X.X系列で発生していると言う認識です
2.8.X.Xではなく、https://zlog.org/download.html　の方の最新版で一度試してください

**Comment by jucky154** [comment]
2.8.8.2の2.8系列の最終バージョンでは起きず、2.9.2.2などでは発生することを考えると

例えばですけど
https://github.com/jr8ppg/zLog/issues/640
でDLLのパスの解決の際に, md5のパスまで変えてしまい、適切なmd5の場所を見なくなって、md5が存在しないよというエラーを吐いているとか？

**Comment by irukabando** [comment]
皆様，ありがとうございます。

![image](https://github.com/user-attachments/assets/94e9276a-b47e-4a87-94d0-2466a86d8e73)
このエラーが出ています。

再現手順としては，
https://zlog.org/download.html から zLog を新しくダウンロード（安定板および開発版の両方を試した）
各種設定 -> プラグインマネージャーから zLog additional O/I をインストール

また，インストール後に，.lg8 ファイルを取り込もうとすると以下のエラーが発生し，一件も取り込めませんでした。
![image](https://github.com/user-attachments/assets/08e02548-6d52-4644-81a5-5640d6be07ec)

よろしくお願いします。

別件ですが，
https://use.zlog.org/downloads.html に最新情報が掲載されていないのですが，更新を休止してるんでしょうか...

**Comment by jucky154** [comment]
@JG1VPP 

2.9.1.5 までは大丈夫そうです。となると、DLL の参照先を絶対パスから指定フォルダに変えた2.9.1.6以後の問題となりそうです
という報告を受けました

**Comment by JG1VPP** [comment]
> https://use.zlog.org/downloads.html に最新情報が掲載されていないのですが，更新を休止してるんでしょうか...

GitHubの都合により、2ヶ月放置すると自動更新が勝手に停止します https://github.com/nextzlog/todo/issues/171

解決策としては、jr8ppg/zLog でGitHub Actionsのワークフローを設定し、リリースの度に [repository_dispatch](https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch)を経由してnextzlog/use.zlog.org の自動更新を要求する方法があります。

**Comment by jr8ppg** [comment]
各位
追試ありがとうございます。改めてやってみます。

**Comment by jr8ppg** [comment]
原因判明。
#640 で[チェックサムの有無フラグを無視](https://github.com/jr8ppg/zLog/blob/312e6b4e7b0dc9cf4227b07847cbfd307fcce612/zlog/UPluginManager.pas#L262)するようにしています。理由は・・・
確かアップデートしたいのに更新されたか判定しないファイルがあって、それでは全く意味が無いのでコメントアウトした物。
さらにmd5ファイルが無くてもエラーにならない不備があったため #640 であわせて修正した。

そうするとzLog additional I/Oではqxsl.exeを使用していて、こいつにはmd5ファイルがなかったもの・・・
https://github.com/autodyne/qxsl/releases/ に https://github.com/autodyne/qxsl/releases/download/nightly/qxsl.exe.md5 があれば良かった・・・

md5ファイル追加して下さい。

**Comment by jr8ppg** [comment]
なお、zLog additional I/Oの https://github.com/nextzlog/zylo/releases/download/nightly/format.dll.md5 の方は自動的にmd5ファイルが用意されるため正常終了します。

**Comment by jr8ppg** [comment]
qxsl.exeのmd5値は以下です。
`39df281f87538040ed31d84936d26caa`

**Comment by JG1VPP** [comment]
@jr8ppg
ご確認ありがとうございます。
zLogマーケットプレイスの仕様が十分に共有できておらず混乱を招き、大変申し訳ありません。

### 結論

`sum`は以下の何れかです。
- md5sum
- md5sumを記載したファイルへのURL

従って、現在のzLogは一部のプラグインを正しく処理できません。

### マーケットプレイスの仕様

[README](https://github.com/nextzlog/zylo?tab=readme-ov-file#publish) に記載の通り、

> First, create a TOML file and include the download URL and md5 checksum in the dll table. **You can include the checksum directly or include the URL of the md5 file**.

```ini
# dll.<name>
[dll.sample]
url = "https://example.com/releases/sample.dll"
sum = "https://example.com/releases/sample.dll.md5"
```

言葉足らずな表現ですが、 `sum` にはmd5sumまたはmd5ファイルのURLを指定します。
例えば、`qxsl.exe`は、[market.json](https://pkg.zlog.org/market.json)で以下の通りに定義されています。

```json
{
 "exe": {
    "format": {
      "sum": "c75402364bf64ef76119d8678ff9a83b",
      "url": "https://github.com/autodyne/qxsl/releases/download/nightly/qxsl.exe"
    }
  }
}
```

従って、`sum`がURLでなければ、md5sumとして読み取るのが仕様通りとなります。
ただし、`qxsl.exe`の更新時に md5sum が更新されずに残る不具合があり、それはサーバ側の問題となります。

仕様の共有が不十分で大変申し訳ありませんでした。

**Comment by JG1VPP** [comment]
ご参考までに、我々が実装した元々の [`UPluginManager.pas`](https://github.com/jr8ppg/zLog/blob/6eb5c2d7c496074bf9e3e998cec069d7494c0eef/zlog/UPluginManager.pas#L315-L322)では、

```delphi
function TMarketItem.CheckSum: string;
begin
	try
		MarketForm.LoadText(Self.sum, Result);
	except
		Result := Self.sum;
	end;
end;
```

としています。ご確認ください。

**Comment by JG1VPP** [comment]
また、zLogマーケットプレイスの仕様上、必ずしもmd5ファイルのURLは `url` + .md5 とはならず、別のホストに所在する場合もあります。従って、必ず `sum` に指定されたmd5ファイルを参照してください。

**Comment by jr8ppg** [comment]
@JG1VPP 
解説ありがとうございます。
ということは #392 での修正方法がイマイチだったと、、、
ちょっと考えます。

**Comment by jr8ppg** [comment]
Item.sumが32バイトならmd5と見なす。それ以外はLoadTextかけてエラーならファイル無しとする。これでOK。

**Comment by JG1VPP** [comment]
@irukabando zLog Additional I/Oプラグインでエラーが表示される原因は、最近のGo言語の[仕様変更](https://github.com/nextzlog/todo/issues/218)にあると判明し、対応しました。zLogを起動して、Plugin ManagerからzLog Additional I/Oプラグインを更新し、zLogを再起動して、Import/Exportを試していただけますでしょうか？

**Comment by irukabando** [comment]
確認遅れてすみません。
zLog Additional I/O のプラグインの更新を何度か試しましたが，以下のエラーが出ました。
![image](https://github.com/user-attachments/assets/1782e984-87bc-46e2-aff5-26eaf223f800)

操作としては以下です。
zLog を立ち上げる
プラグインマネージャーのウィンドウを立ち上げる
zLog Additional A/O を選択し，無効にするを押したあと，インストールを押した
zLog をたち下げたのちに起動
ファイル -> インポートから lg8 ファイルを選択
その後，エラーが出た

よろしくお願いします。
