### ISSUE TITLE
インターネット不通時にプラグインマネージャを開くとエラーダイアログが表示される

### ISSUE THREAD

**Issue by JG1VPP** [jr8ppg/zLog#715]
`UPluginManager.pas`の[`TMarketForm.LoadJSON`](https://github.com/jr8ppg/zLog/blob/312e6b4e7b0dc9cf4227b07847cbfd307fcce612/zlog/UPluginManager.pas#L407-L417)メソッドに例外処理を追加いただけますか？

**Comment by jr8ppg** [comment]
了解です

**Comment by jr8ppg** [comment]
以前の修正はいまいちでした。
