### ISSUE TITLE
AMDインターフェースの検証

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#72]
AMDインターフェースの件の検証
http://jn2amd.html.xdomain.jp/usbrigcwsound40.htm

双方共にKEY:DTR, PTT:RTSなのにキーイングできないとは？

誰か持っていませんか？

**Comment by 7M4KSC** [comment]
[PCWI01](https://www.jh4vaj.com/pcwi01_01)のDTR->Keyは動作しているので、AMDインターフェース ver.4でも、動作するハズですが、どうも頒布されていない？（「配布」のページに、ver.4の頒布情報が掲載されていません）
もうちょっと、回路を見てみます。

**Comment by jr8ppg** [comment]
調査ありがとうございます。RI, DCD, DSRは使ってないですね。
理屈上は動く物と考えています。
もし関係があるとすればDSRかと思いますが、データを送らないので関係なさそうです。
前にAMDさんに聞いてもらったことがあるのですが、動作テストした状況とかが不明でした。
現物で追試するしか無いと思っています。

**Comment by 7M4KSC** [comment]
AMD-USB-RIG-CW-SOUND Ver4.0の頒布に関して、AMD OMにメールを出しました。

**Comment by 7M4KSC** [comment]
ＡＭＤ－ＲＳ２３２Ｃ－ＳＯＵＮＤ　Ｖｅｒ１．０では、zLogで(RISC CPU USBでは無く)DTRでキーイングされているので、どうも最近のAMD OMのインターフェースでは、本当にキーイング出来ないみたいです。ちょっと本気で、入手してみますかね。

**Comment by jr8ppg** [comment]
？？
なんで駄目なんですかね。不思議です。

**Comment by 7M4KSC** [comment]
ちょっと遅くなりましたが、ＡＭＤ－ＵＳＢ－ＲＩＧ－ＣＷ－ＳＯＵＮＤ　Ｖｅｒ３．５の完成品
を注文しました。（各IFの違いがよくわかって無くて、発注遅延～）

**Comment by 7M4KSC** [comment]
上記、AMD-USB-RIG-CW-SOUND Ver3.5で、CWのキーイングが出来る事を2.6 beta1で確認しました。

**Comment by 7M4KSC** [comment]
AMD OMに動作した事を報告済みなので、closeでも良いかと思います。

**Comment by jr8ppg** [comment]
了解しました。ありがとうございます。
