### ISSUE TITLE
WAEコンテストの動作確認

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#73]
WAEコンテストの動作確認
QTC送信機能は未完成？
動作するとは思えない感じですが、、、

**Comment by 7M4KSC** [comment]
WAEDCのRTTY（2020/11/14）では無く、CWで、ということですよね。
明日以降にやってみます。QTCが面倒で、やった事無い（し、現環境ではそもそも大陸間交信出来ない・・・）。

**Comment by jr8ppg** [comment]
CWですね。ソース見た感じでは完成しているようには見えないんですよね。マニュアルにはQTCのやり方とか書いてありますが、、、
直す気も無いので深入り不要です．．．

**Comment by jr8ppg** [comment]
#670 で対応する
