### ISSUE TITLE
Help > About... で「The file (パス名) Does not exist.」

### ISSUE THREAD

**Issue by jj1cvh** [jr8ppg/zLog#75]
※ Issue作成テストを兼ねて、再現性が不確かな不具合を報告しています

(zLogバージョン) 2.5.0.6
(PC環境) Win8.1 64bit

(現象)
zlogのzipフォルダを展開してzlog.exeを一度実行(Windows DefenderのPC保護表示画面から実行)した後、zlog.exeのフォルダを移動すると、Help > About... で
The file
 C:¥Users¥{ユーザ名}¥Documents¥zlogwin_2500_20200928
Does not exist.
というエラーメッセージが表示され、[OK]を押すとAbout画面が表示される。
このときのAbout画面は、May 23,2005 の右に「全市全郡コンテスト」のように表示されるべきところ「Label2」と表示される。

(再現手順) 不明、要再検証

**Comment by jr8ppg** [comment]
V2.9ではフォルダの移動やリネームができないので、もう起きないように思います．．．
