### ISSUE TITLE
QSO修正で得点が修正できない

### ISSUE THREAD

**Issue by jr8ppg** [jr8ppg/zLog#80]
交信リストダブルクリックでのQSO修正ウインドウでで得点を変更しても修正されない。
DUPE交信は得点を0にできる。

**Comment by js2ggd** [comment]
得点は常に再計算されているようなので、手動で修正できるように変更するより、DUPE以外にも、特定の条件（ナンバー欄が空白、もしくは不正な値になっている、など）の場合に無得点とするように修正したほうが良いかもしれません。

**Comment by jr8ppg** [comment]
任意の点数に変更したい話ありませんでしたっけ？

**Comment by js2ggd** [comment]
いろいろなケースが考えられますが、過大な得点や数値以外の文字を誤って入力してしまう恐れもあるので、任意の点数を入力できるようにするのはかえって危険ではないか、と思い至りました。
基本的に、交信記録に基づいて(任意の記録を修正した後も)自動で得点やマルチが再計算されるようなので、参加バンド・モード内の「無効とする交信」をナンバー欄で判定し無得点とするようにすれば、実用的には充分かつ安全と思いますがいかがでしょうか。

**Comment by jr8ppg** [comment]
改めてメールを読み返してみると、０でよさそうですね。
それなら #83 も含めて対応できそうです。

**Comment by jr8ppg** [comment]
これはクローズで
