### ISSUE TITLE
ナンバーが Band毎 Serial の場合の問題

### ISSUE THREAD

**Issue by js2ggd** [jr8ppg/zLog#84]
コンテストナンバーがバンド毎にシリアルナンバー(001形式)を送る形式の場合、定義ファイル(cfg)に

serial	band;

を書くと実現できるが、ログデータを保存してzLogを一旦終了し、再度ファイルを読み込むと、最後の行に記録したバンド以外のバンドのナンバーが001に戻ってしまう。

**Comment by jr8ppg** [comment]
それは直しました。
https://github.com/jr8ppg/zLog/commit/add6741d50cbc0e9f1843b3ed6ffef73e1565333

**Comment by js2ggd** [comment]
ありがとうございます。
