### ISSUE TITLE
OmniRigを選択するとTrapする

### ISSUE THREAD

**Issue by 7M4KSC** [jr8ppg/zLog#85]
OmniRigを選択するとTrapしますが、詳しい手順は後ほど。
なお、OmniRig V1を入れていますが、正しいでしょうか？
[OmniRig download]
http://www.dxatlas.com/
[入れ方]
https://jm1xtk.dip.jp/cnt/71_omnirig/index.php
[症状]
OmniRig V1を(例えば)IC-7000に対して導入。Release 2.5.0.0。
RigをOmniRigに設定し、
Use Tranceive Mode(ICOM only)とGet band and mode alternately(ICOM only)のチェックを
外してOKを押すと、trapする。
ICOMの場合、OmniRigでモードは取れるが、周波数が取れない模様。

**Comment by jr8ppg** [comment]
残念ながらOmniRigは一度も動かしたことありません。

**Comment by 7M4KSC** [comment]
了解です、JR1LQKさんのmasterにもOmniRigの残骸があるのですが、旧zlog ver.2.2eには選択肢が無いので、旧zLogのその後の開発途中で、作成中止なった様ですね。時期からして、OmniRig V1なのは判明しました。

**Comment by 7M4KSC** [comment]
http://www.dxatlas.com/OmniRig/ のOmniRig Clientを立ち上げると、IC-7000の周波数/modeも制御出来るので、
一度八重洲のリグでやってみます。（時間かかります、Hi）
OmniRigが動作すると、アルインコ、Elecraft、Ten-Tec辺りが救えます。

**Comment by jj1cvh** [comment]
HDSDRとCW SkimmerでOmniRigをちょっと使ったことがある程度の経験値しかありませんが、zLogがOmniRig対応になると、zLog以外のOmniRig対応ソフトとzLogがVSPEを使わずにリグコンを共用できるはず、という点で本件(#85)には興味を持っています。

JR1LQK/zLogが公開されたときにOmniRigが含まれているのを見た時の私の印象は、zLogのリグコンはOmniRigのソースコードを活用してたのね、ということでした。
ソースコードをちゃんと追いかけた訳ではありませんが、残骸というよりむしろzLogのリグコンの本体という気がします。

ちなみにOmniRigのソースコードはDelphiでgithubに公開されてるようです。
https://github.com/VE3NEA/OmniRig

Delphi5のサンプルプログラムも配布されています。
http://www.dxatlas.com/OmniRig/

**Comment by 7M4KSC** [comment]
なんと、VSPE使わずに、共用できるかもしれないのですね。興味沸いてきました。
残骸というのはちょっと言い過ぎました、icomでもモードは取得出来ていたので、zLog本体の方を見てみます。
色々情報ありがとうございます。

**Comment by jr8ppg** [comment]
OmniRig_TLB.pasというファイルがあるのですが、これを最新のOmniRigのTypeLibから再度作成して入れ替えれば動くかな～と思います。そこまでは調べたのです。

**Comment by jr8ppg** [comment]
最新のOmniRigをインストールしてOmniRig_TLB.pasを再作成した物の、色々違いすぎて中断。参ったなー。

**Comment by jr8ppg** [comment]
インポートの仕方が駄目だった。やり直してOmniRig_TLB.pas差し替え成功。

**Comment by 7M4KSC** [comment]
AMD-USB-RIG-CW-SOUND Ver3.5とTS-850Sを繋ぎ、zLog 2.6 beta1 releaseでTS-850を正常の制御出来る事を確認した後に、OmniRig経由にしてみましたが、ICOMと同じく周波数制御が出来ずに、Trapしますね。新しい、OmniRig_TLB.pasの方でやってみますが、これは、OmniRig V2の物なのでしょうか？

**Comment by jr8ppg** [comment]
えーと、OmniRig V1.19と出ました。
これで良いですよね、、、

**Comment by jr8ppg** [comment]
あーわかりました。
分岐したV2があるのですね。
http://www.hb9ryz.ch/multirig/index.html

**Comment by jr8ppg** [comment]
手直しをして例外が飛ばないようにしました。
OmniRIg V1.19 + FT-2000でとりあえず動きました。

**Comment by 7M4KSC** [comment]
ビルド環境を再構築し、winkeyerブランチをビルドしたところ、OmniRig V1で、TS-850が動作しました！
周波数を取得出来るのも確認しました。修正ありがとうございました。いったんcloseします。

**Comment by 7M4KSC** [comment]
OmniRigで動作し、TRAPしなくなったので、クローズとします。
確認機種、FT-2000, TS-850
