### ISSUE TITLE
サウンドデバイスが存在しない状態では一般保護エラーが出て起動できない

### ISSUE THREAD

**Issue by JO3JYE** [jr8ppg/zLog#99]
サウンドデバイス(再生デバイス)が存在しない状態で起動すると、一般保護エラーのホップアップが出続ける。止めるにはタスクマネージャーにてプロセスの停止しかない。

winkeyブランチのコードをビルドし、たまたまサウンドデバイスの無いPCで起動したことで気が付きました。
voice機能やサイドトーンを復活したあたりから、この問題があると思われます。
昨夏(FDの頃)にビルドした実行ファイルだと、サウンドデバイスが存在しなくても正常に起動できます。

再現方法は、コントロールパネル→サウンド→再生　にて、すべてのデバイスを無効にすれば良いかと思います。

**Comment by jr8ppg** [comment]
現象確認

**Comment by jr8ppg** [comment]
サウンドデバイスが無い場合はサイドトーン出ない様にしました。VOICE機能は使わないで下さい。

**Comment by JO3JYE** [comment]
事象解消を確認しました。ありがとうございました！
